// 表情包模板数据
const emojiTemplates = [
  { main: '一只在电脑前面顶着黑眼圈的疲惫的狗', caption: '加班狗' },
  { main: '一只对着bug抓狂的程序猿', caption: '代码一把梭' },
  { main: '一只对着PPT打瞌睡的考拉', caption: '会议困困' },
  { main: '一只对着工作群疯狂点头的鸡', caption: '好的老板' },
  { main: '一只对着月亮嚎叫的狼', caption: '又要干到天亮' },
  { main: '一只抱着咖啡发抖的松鼠', caption: '提神醒脑' },
  { main: '一只对着工资条失望的猫', caption: '工资到手' },
  { main: '一只被任务压垮的小熊', caption: '需求爆炸' },
  { main: '一只对着日历叹气的兔子', caption: '周一病犯' },
  { main: '一只被老板支配的小狗', caption: '恐惧.jpg' },
  { main: '一只对着KPI抓狂的猴子', caption: '指标在燃烧' },
  { main: '一只对着工位疯狂加班的熊猫', caption: '内卷王者' },
  { main: '一只被工作压弯腰的长颈鹿', caption: '压力山大' },
  { main: '一只对着电脑傻笑的小丑鱼', caption: '假装很忙' },
  { main: '一只被截止日期追赶的羚羊', caption: 'DDL追魂' },
  { main: '一只对着打卡机狂奔的企鹅', caption: '迟到危机' },
  { main: '一只被群聊轰炸的小猪', caption: '消息爆炸' },
  { main: '一只对着工作计划崩溃的浣熊', caption: '计划破产' },
  { main: '一只被开会支配的北极熊', caption: '会议人生' },
  { main: '一只对着邮件发呆的树懒', caption: '摸鱼时刻' },
  { main: '一只被客户投诉的小狐狸', caption: '委屈巴巴' },
  { main: '一只对着报表抓狂的小羊', caption: '数据爆炸' },
  { main: '一只被领导表扬的孔雀', caption: '得意忘形' },
  { main: '一只对着工作群装忙的猫头鹰', caption: '在线勿扰' },
  { main: '一只被工作压得喘不过气的河马', caption: '压力爆表' },
  { main: '一只对着工资条流泪的小鸭', caption: '月光族' },
  { main: '一只被任务追着跑的小鹿', caption: '忙到飞起' },
  { main: '一只对着电脑屏幕发呆的熊', caption: '思考人生' },
  { main: '一只被工作榨干的橙子', caption: '能量耗尽' },
  { main: '一只对着工位装深沉的猫', caption: '高端打工' },
  { main: '一只被项目追着跑的兔子', caption: '项目狂奔' },
  { main: '一只对着工作群装死的考拉', caption: '已读不回' },
  { main: '一只被绩效考核吓到的仓鼠', caption: '惊恐面具' },
  { main: '一只对着工作摸鱼的企鹅', caption: '摸鱼达人' },
  { main: '一只被需求变更气晕的狗', caption: '需求又改' },
  { main: '一只对着工作装专业的猴子', caption: '专业选手' },
  { main: '一只被会议轰炸的小象', caption: '会议疲劳' },
  { main: '一只对着工作装忙的狐狸', caption: '忙里偷闲' },
  { main: '一只被工作压垮的小驴', caption: '累成狗了' },
  { main: '一只对着工作装孤独的狼', caption: '独狼战士' },
  { main: '一只被工作追着跑的小猪', caption: '疯狂奔跑' },
  { main: '一只对着工作装淡定的猫', caption: '淡定如我' },
  { main: '一只被工作压得喘不过气的熊', caption: '压力山大' },
  { main: '一只对着工作装高冷的狐狸', caption: '高冷打工' },
  { main: '一只被工作追着跑的小鸡', caption: '忙成陀螺' },
  { main: '一只对着工作装可爱的兔子', caption: '卖萌打工' },
  { main: '一只被工作压垮的小象', caption: '崩溃边缘' },
  { main: '一只对着工作装优雅的天鹅', caption: '优雅职场' },
  { main: '一只被工作追着跑的小羊', caption: '疯狂工作' },
  { main: '一只对着工作装沉思的猫头鹰', caption: '沉思打工' },
  { main: '一只被工作压得喘不过气的小狗', caption: '透不过气' },
  { main: '一只对着工作电脑打游戏的熊猫', caption: '摸鱼高手' },
  { main: '一只假装在键盘上打字的猫', caption: '假装敲代码' },
  { main: '一只对着工作群发表情包的狗', caption: '社交达人' },
  { main: '一只躲在工位后面吃零食的仓鼠', caption: '偷吃现场' },
  { main: '一只对着会议室装睡的考拉', caption: '假装认真听' },
  { main: '一只对着老板疯狂点头的鸡', caption: '老板说得对' },
  { main: '一只对着工作装深沉的猫头鹰', caption: '我很专业' },
  { main: '一只被工作群轰炸的小狗', caption: '@全体成员' },
  { main: '一只对着工位自拍的孔雀', caption: '朋友圈打卡' },
  { main: '一只对着工作日历崩溃的猴子', caption: '假期在哪里' },
  { main: '一只被需求追着跑的兔子', caption: '产品经理别追' },
  { main: '一只对着bug装傻的狐狸', caption: '我啥都不知道' },
  { main: '一只对着工作群秒回的小鸡', caption: '在线秒回' },
  { main: '一只对着工位装酷的老虎', caption: '我很忙的' },
  { main: '一只被工作压成饼的熊猫', caption: '扁平化管理' },
  { main: '一只对着工作装忙的树懒', caption: '极限摸鱼' },
  { main: '一只被需求追着跑的羊驼', caption: '需求爆炸' },
  { main: '一只对着工作装可爱的小猪', caption: '卖萌求饶' },
  { main: '一只被工作追着跑的小鸭', caption: '疯狂逃窜' },
  { main: '一只对着工作装沉思的狗', caption: '假装思考' }
];

// 获取随机模板
function getRandomTemplate() {
  const randomIndex = Math.floor(Math.random() * emojiTemplates.length);
  return emojiTemplates[randomIndex];
}

// 使用 module.exports 导出
module.exports = {
  emojiTemplates,
  getRandomTemplate
}; 